defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:

development:
  <<: *defaults
  database: auth_development

test:
  <<: *defaults
  database: auth_test

production:
  <<: *defaults
  database: auth_production